# Week 02 LAB ACTIVITY

### Lists

In [37]:
fruit = ['apple', 'banana', 'cherry', 'durian', 'elderberry']

print(f"Element at index 1: {fruit[1]}")
print(f"Element at index -2: {fruit[-2]}")
print(f"First two elements: {fruit[:2]}")
print(f"All elements starting fom index 3: {fruit[3:]}")
print(f"Elements from index 1 to 4: {fruit[1:4]}")

Element at index 1: banana
Element at index -2: durian
First two elements: ['apple', 'banana']
All elements starting fom index 3: ['durian', 'elderberry']
Elements from index 1 to 4: ['banana', 'cherry', 'durian']

In [57]:
fruit.append("blueberry")
print(fruit)

# the append method adds a new element in list.

['apple', 'banana', 'cherry', 'durian', 'elderberry', 'blueberry']

In [58]:
fruit.count("banana")

# the count method returns the no of times the element has occured in the list.

1

In [59]:
print(fruit)
fruit.pop()
print(fruit)

['apple', 'banana', 'cherry', 'durian', 'elderberry', 'blueberry']
['apple', 'banana', 'cherry', 'durian', 'elderberry']

### Manipulating Data with Pandas

#### 1.

In [124]:
import pandas as pd

In [125]:
df = pd.DataFrame({
    "Student": ["Vaibav","Ayan","Ayush","Rachel"],
    "Age": [23,26,19,21],
    "Grade": ["A","B","A","C"],
    "Score": [90,75,92,65],
    "Enrolled": pd.to_datetime(["2025-09-09","2025-08-01","2025-07-01","2025-10-01"])
})
df.head()

  Student  Age Grade  Score   Enrolled
0  Vaibav   23     A     90 2025-09-09
1    Ayan   26     B     75 2025-08-01
2   Ayush   19     A     92 2025-07-01
3  Rachel   21     C     65 2025-10-01

#### 2.

In [126]:
new_row = pd.DataFrame({
    "Student": ["Adithya"],
    "Age": [18],
    "Grade": ["A"],
    "Score": [99],
    "Enrolled": pd.to_datetime(["2025-09-10"])
})
new_row.head()

   Student  Age Grade  Score   Enrolled
0  Adithya   18     A     99 2025-09-10

In [127]:
df = pd.concat([df,new_row],ignore_index=True)
df.head()

   Student  Age Grade  Score   Enrolled
0   Vaibav   23     A     90 2025-09-09
1     Ayan   26     B     75 2025-08-01
2    Ayush   19     A     92 2025-07-01
3   Rachel   21     C     65 2025-10-01
4  Adithya   18     A     99 2025-09-10

#### 3.

In [128]:
df.dtypes

Student                str
Age                  int64
Grade                  str
Score                int64
Enrolled    datetime64[us]
dtype: object

#### 4.

In [129]:
df.head(3)

  Student  Age Grade  Score   Enrolled
0  Vaibav   23     A     90 2025-09-09
1    Ayan   26     B     75 2025-08-01
2   Ayush   19     A     92 2025-07-01

In [130]:
df.tail(2)

   Student  Age Grade  Score   Enrolled
3   Rachel   21     C     65 2025-10-01
4  Adithya   18     A     99 2025-09-10

#### 5.

In [131]:
df["Age"]

0    23
1    26
2    19
3    21
4    18
Name: Age, dtype: int64

In [132]:
df[["Age","Grade"]]

   Age Grade
0   23     A
1   26     B
2   19     A
3   21     C
4   18     A

#### 6.

In [133]:
df.loc[2]

Student                   Ayush
Age                          19
Grade                         A
Score                        92
Enrolled    2025-07-01 00:00:00
Name: 2, dtype: object

In [134]:
df.loc[0:3]

  Student  Age Grade  Score   Enrolled
0  Vaibav   23     A     90 2025-09-09
1    Ayan   26     B     75 2025-08-01
2   Ayush   19     A     92 2025-07-01
3  Rachel   21     C     65 2025-10-01

In [135]:
df[["Age","Grade"]].loc[0:3]

   Age Grade
0   23     A
1   26     B
2   19     A
3   21     C

#### 7.

In [136]:
df[["Student","Enrolled"]].tail(3)

   Student   Enrolled
2    Ayush 2025-07-01
3   Rachel 2025-10-01
4  Adithya 2025-09-10

#### 8.

In [137]:
df[df["Grade"] == "B"]

  Student  Age Grade  Score   Enrolled
1    Ayan   26     B     75 2025-08-01

In [138]:
df[df["Age"] >= 21]

  Student  Age Grade  Score   Enrolled
0  Vaibav   23     A     90 2025-09-09
1    Ayan   26     B     75 2025-08-01
3  Rachel   21     C     65 2025-10-01

In [139]:
score_df = df[df["Score"] > 70]
score_df[score_df["Score"] < 85][["Grade","Age"]]

  Grade  Age
1     B   26

In [140]:
df[df["Enrolled"] > "2025-09-01"].Student

0     Vaibav
3     Rachel
4    Adithya
Name: Student, dtype: str

In [141]:
df[df["Grade"] != "A"].Enrolled

1   2025-08-01
3   2025-10-01
Name: Enrolled, dtype: datetime64[us]

#### 9.

In [164]:
df.sort_values(by = "Score",inplace=True,ignore_index=True)
df.head()

   Student  Age Grade  Score   Enrolled
0   Rachel   21     C     65 2025-10-01
1     Ayan   26     B     75 2025-08-01
2   Vaibav   23     A     90 2025-09-09
3    Ayush   19     A     92 2025-07-01
4  Adithya   18     A     99 2025-09-10

In [165]:
df.sort_values(by = "Score",inplace=True,ascending=False,ignore_index=True)
df.head()

   Student  Age Grade  Score   Enrolled
0  Adithya   18     A     99 2025-09-10
1    Ayush   19     A     92 2025-07-01
2   Vaibav   23     A     90 2025-09-09
3     Ayan   26     B     75 2025-08-01
4   Rachel   21     C     65 2025-10-01

In [167]:
df.sort_values(by = "Grade",inplace = True,ignore_index=True)
df.head()

   Student  Age Grade  Score   Enrolled
0  Adithya   18     A     99 2025-09-10
1    Ayush   19     A     92 2025-07-01
2   Vaibav   23     A     90 2025-09-09
3     Ayan   26     B     75 2025-08-01
4   Rachel   21     C     65 2025-10-01

In [ ]:
df.sort_values(by = "Age",inplace = True,ignore_index=True,ascending=False)
df.head()

   Student  Age Grade  Score   Enrolled
0     Ayan   26     B     75 2025-08-01
1   Vaibav   23     A     90 2025-09-09
2   Rachel   21     C     65 2025-10-01
3    Ayush   19     A     92 2025-07-01
4  Adithya   18     A     99 2025-09-10

### Importing Dataset in Pandas

#### Step 1

In [171]:
flights = pd.read_csv("https://vincentarelbundock.github.io/Rdatasets/csv/nycflights13/flights.csv")
flights.head()

,rownames,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,1,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,3,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,4,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,5,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z

#### Step 2

In [173]:
flights.describe()

,rownames,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,flight,air_time,distance,hour,minute
count,336776.000000,336776.0,336776.000000,336776.000000,328521.000000,336776.000000,328521.000000,328063.000000,336776.000000,327346.000000,336776.000000,327346.000000,336776.000000,336776.000000,336776.000000
mean,168388.500000,2013.0,6.548510,15.710787,1349.109947,1344.254840,12.639070,1502.054999,1536.380220,6.895377,1971.923620,150.686460,1039.912604,13.180247,26.230100
std,97219.001466,0.0,3.414457,8.768607,488.281791,467.335756,40.210061,533.264132,497.457142,44.633292,1632.471938,93.688305,733.233033,4.661316,19.300846
min,1.000000,2013.0,1.000000,1.000000,1.000000,106.000000,-43.000000,1.000000,1.000000,-86.000000,1.000000,20.000000,17.000000,1.000000,0.000000
25%,84194.750000,2013.0,4.000000,8.000000,907.000000,906.000000,-5.000000,1104.000000,1124.000000,-17.000000,553.000000,82.000000,502.000000,9.000000,8.000000
50%,168388.500000,2013.0,7.000000,16.000000,1401.000000,1359.000000,-2.000000,1535.000000,1556.000000,-5.000000,1496.000000,129.000000,872.000000,13.000000,29.000000
75%,252582.250000,2013.0,10.000000,23.000000,1744.000000,1729.000000,11.000000,1940.000000,1945.000000,14.000000,3465.000000,192.000000,1389.000000,17.000000,44.000000
max,336776.000000,2013.0,12.000000,31.000000,2400.000000,2359.000000,1301.000000,2400.000000,2359.000000,1272.000000,8500.000000,695.000000,4983.000000,23.000000,59.000000

In [174]:
flights.shape

(336776, 20)

In [187]:
flights.dtypes

rownames            int64
year                int64
month               int64
day                 int64
dep_time          float64
sched_dep_time      int64
dep_delay         float64
arr_time          float64
sched_arr_time      int64
arr_delay         float64
carrier               str
flight              int64
tailnum               str
origin                str
dest                  str
air_time          float64
distance            int64
hour                int64
minute              int64
time_hour             str
dtype: object

In [176]:
flights.isnull().sum()

rownames             0
year                 0
month                0
day                  0
dep_time          8255
sched_dep_time       0
dep_delay         8255
arr_time          8713
sched_arr_time       0
arr_delay         9430
carrier              0
flight               0
tailnum           2512
origin               0
dest                 0
air_time          9430
distance             0
hour                 0
minute               0
time_hour            0
dtype: int64

In [204]:
flights.dropna(how = "any",inplace = True)
flights.isnull().sum()

rownames          0
year              0
month             0
day               0
dep_time          0
sched_dep_time    0
dep_delay         0
arr_time          0
sched_arr_time    0
arr_delay         0
carrier           0
flight            0
tailnum           0
origin            0
dest              0
air_time          0
distance          0
hour              0
minute            0
time_hour         0
dtype: int64

#### Q1.

In [205]:
q1 = flights[flights["dep_delay"] >=120]
q1.head()

,rownames,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
151,152,2013,1,1,848.0,1835,853.0,1001.0,1950,851.0,MQ,3944,N942MQ,JFK,BWI,41.0,184,18,35,2013-01-01T23:00:00Z
218,219,2013,1,1,957.0,733,144.0,1056.0,853,123.0,UA,856,N534UA,EWR,BOS,37.0,200,7,33,2013-01-01T12:00:00Z
268,269,2013,1,1,1114.0,900,134.0,1447.0,1222,145.0,UA,1086,N76502,LGA,IAH,248.0,1416,9,0,2013-01-01T14:00:00Z
491,492,2013,1,1,1540.0,1338,122.0,2020.0,1825,115.0,B6,705,N570JB,JFK,SJU,193.0,1598,13,38,2013-01-01T18:00:00Z
649,650,2013,1,1,1815.0,1325,290.0,2120.0,1542,338.0,EV,4417,N17185,EWR,OMA,213.0,1134,13,25,2013-01-01T18:00:00Z

#### Q2.

In [206]:
q2 = flights[flights["dest"] == "IAH"]
q2_ = flights[flights["dest"] == "HOU"]
q2 = pd.concat([q2,q2_])
q2.head()

,rownames,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,1,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
32,33,2013,1,1,623.0,627,-4.0,933.0,932,1.0,UA,496,N459UA,LGA,IAH,229.0,1416,6,27,2013-01-01T11:00:00Z
81,82,2013,1,1,728.0,732,-4.0,1041.0,1038,3.0,UA,473,N488UA,LGA,IAH,238.0,1416,7,32,2013-01-01T12:00:00Z
89,90,2013,1,1,739.0,739,0.0,1104.0,1038,26.0,UA,1479,N37408,EWR,IAH,249.0,1400,7,39,2013-01-01T12:00:00Z

#### Q3.

In [207]:
q3 = flights[flights["arr_delay"] > 120]
q3 = q3[q3["dep_delay"] <= 0]
q3.head()

,rownames,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
22911,22912,2013,1,27,1419.0,1420,-1.0,1754.0,1550,124.0,MQ,3728,N1EAMQ,EWR,ORD,135.0,719,14,20,2013-01-27T19:00:00Z
33011,33012,2013,10,7,1350.0,1350,0.0,1736.0,1526,130.0,EV,5181,N611QX,LGA,MSN,117.0,812,13,50,2013-10-07T17:00:00Z
33019,33020,2013,10,7,1357.0,1359,-2.0,1858.0,1654,124.0,AA,1151,N3CMAA,LGA,DFW,192.0,1389,13,59,2013-10-07T17:00:00Z
41075,41076,2013,10,16,657.0,700,-3.0,1258.0,1056,122.0,B6,3,N703JB,JFK,SJU,225.0,1598,7,0,2013-10-16T11:00:00Z
55985,55986,2013,11,1,658.0,700,-2.0,1329.0,1015,194.0,VX,399,N629VA,JFK,LAX,336.0,2475,7,0,2013-11-01T11:00:00Z

#### Q4.

In [210]:
flights["time_gained"] = flights["dep_delay"] - flights["arr_delay"]

q4 = flights[flights["dep_delay"]>=60]
q4 = q4[q4["time_gained"] > 30]
q4.head()

,rownames,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,time_gained
815,816,2013,1,1,2205.0,1720,285.0,46.0,2040,246.0,...,1999,N5DNAA,EWR,MIA,146.0,1085,17,20,2013-01-01T22:00:00Z,39.0
832,833,2013,1,1,2326.0,2130,116.0,131.0,18,73.0,...,199,N594JB,JFK,LAS,290.0,2248,21,30,2013-01-02T02:00:00Z,43.0
2286,2287,2013,1,3,1503.0,1221,162.0,1803.0,1555,128.0,...,551,N835UA,EWR,SFO,320.0,2565,12,21,2013-01-03T17:00:00Z,34.0
2508,2509,2013,1,3,1839.0,1700,99.0,2056.0,1950,66.0,...,575,N631AA,JFK,EGE,239.0,1747,17,0,2013-01-03T22:00:00Z,33.0
2522,2523,2013,1,3,1850.0,1745,65.0,2148.0,2120,28.0,...,177,N332AA,JFK,SFO,314.0,2586,17,45,2013-01-03T22:00:00Z,37.0

#### Q5.

In [213]:
airtime = flights[flights["air_time"] > 0]
flights["avg_mph"] = flights["distance"] / airtime["air_time"]
flights.head()

,rownames,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,time_gained,avg_mph
0,1,2013,1,1,517.0,515,2.0,830.0,819,11.0,...,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z,-9.0,6.167401
1,2,2013,1,1,533.0,529,4.0,850.0,830,20.0,...,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z,-16.0,6.237885
2,3,2013,1,1,542.0,540,2.0,923.0,850,33.0,...,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z,-31.0,6.806250
3,4,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,...,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z,17.0,8.612022
4,5,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,...,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z,19.0,6.568966

In [ ]:
q5 = flights.sort_values(by = ["avg_mph"],ascending=False)
q5.head()

,rownames,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,time_gained,avg_mph
216447,216448,2013,5,25,1709.0,1700,9.0,1923.0,1937,-14.0,...,N666DN,LGA,ATL,65.0,762,17,0,2013-05-25T21:00:00Z,23.0,11.723077
251999,252000,2013,7,2,1558.0,1513,45.0,1745.0,1719,26.0,...,N17196,EWR,MSP,93.0,1008,15,13,2013-07-02T19:00:00Z,19.0,10.838710
205388,205389,2013,5,13,2040.0,2025,15.0,2225.0,2226,-1.0,...,N14568,EWR,GSP,55.0,594,20,25,2013-05-14T00:00:00Z,16.0,10.800000
157516,157517,2013,3,23,1914.0,1910,4.0,2045.0,2043,2.0,...,N12567,EWR,BNA,70.0,748,19,10,2013-03-23T23:00:00Z,2.0,10.685714
10223,10224,2013,1,12,1559.0,1600,-1.0,1849.0,1917,-28.0,...,N956DL,LGA,PBI,105.0,1035,16,0,2013-01-12T21:00:00Z,27.0,9.857143

#### Q6.

In [215]:
q6 = flights.sort_values(by = ["time_gained"],ascending=False)
q6.head()

,rownames,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,time_gained,avg_mph
234102,234103,2013,6,13,1907.0,1512,235.0,2134.0,1928,126.0,...,N19554,EWR,JAX,126.0,820,15,12,2013-06-13T19:00:00Z,109.0,6.507937
133681,133682,2013,2,26,1000.0,900,60.0,1513.0,1540,-27.0,...,N382HA,JFK,HNL,584.0,4983,9,0,2013-02-26T14:00:00Z,87.0,8.532534
131143,131144,2013,2,23,1226.0,900,206.0,1746.0,1540,126.0,...,N389HA,JFK,HNL,599.0,4983,9,0,2013-02-23T14:00:00Z,80.0,8.318865
205312,205313,2013,5,13,1917.0,1900,17.0,2149.0,2251,-62.0,...,N721TW,JFK,SFO,313.0,2586,19,0,2013-05-13T23:00:00Z,79.0,8.261981
134562,134563,2013,2,27,924.0,900,24.0,1448.0,1540,-52.0,...,N389HA,JFK,HNL,589.0,4983,9,0,2013-02-27T14:00:00Z,76.0,8.460102

### HOMEWORK